[build]
  command = "gatsby build"
  publish = "public"

[dev]
  command = "gatsby develop"

[[redirects]]
  from = "https://countdown-elk.netlify.com/*"
  to = "https://countdown.elk.sh/:splat"
  status = 301
  force = true